In [6]:
import numpy as np
import pandas as pd

In [9]:
df = pd.read_csv("spam.csv", encoding="latin-1")

In [10]:
df.sample(5)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
3866,ham,"Alright we're hooked up, where you guys at",NaN,NaN,NaN
3495,ham,Happy birthday... May u find ur prince charmin...,NaN,NaN,NaN
239,spam,U 447801259231 have a secret admirer who is lo...,NaN,NaN,NaN
5105,ham,I wnt to buy a BMW car urgently..its vry urgen...,NaN,NaN,NaN
2806,spam,December only! Had your mobile 11mths+? You ar...,NaN,NaN,NaN

In [11]:
df.shape

(5572, 5)

# Data Cleaning

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 217.8 KB

In [13]:
# drop last 3 cols
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [14]:
df.sample(5)

        v1                                                 v2
3940  spam  Free Msg: get Gnarls Barkleys \Crazy\" rington...
4547   ham  Hope you are having a good week. Just checking in
4681   ham              Haha yeah, 2 oz is kind of a shitload
4086  spam  PRIVATE! Your 2003 Account Statement for 07973...
3862  spam  Oh my god! I've found your number again! I'm s...

In [15]:
# renaming the columns 
df.rename(columns={'v1':'target', 'v2':'text'},inplace=True)
df.sample(5)

     target                                               text
1249    ham  I call you later, don't have network. If urgnt...
3270   spam  You have 1 new voicemail. Please call 08719181...
2169   spam  Shop till u Drop, IS IT YOU, either 10K, 5K, å...
5527    ham  Total disappointment, when I texted you was th...
2095    ham                    Probably, want to pick up more?

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()